### ISSUE TITLE
Bug - In use

### ISSUE THREAD

**Issue by crymates** [me4502/SlotMachines#8]
Hey ;]

There's an handle problem which causes the "in use" error, when u played an game and wanna start a new one.
I think there's an problem when the plugin tries to check for balance and idk sync probs ^^

Here's my log:
```
[22:17:24] [Server thread/ERROR] [Sponge/]: The Scheduler tried to run the task slotmachines-S-6 owned by Plugin{id=slotmachines, name=SlotMachines, version=1.0, description=SlotMachines for Sponge, authors=[Me4502], source=/home/servers/sponge_mc/mods/SlotMachines-1.0.jar}, but an error occured.
java.lang.NullPointerException
	at net.minecraft.entity.item.EntityItemFrame.func_174864_a(EntityItemFrame.java:165) ~[yz.class:?]
	at net.minecraft.entity.item.EntityItemFrame.func_82334_a(EntityItemFrame.java:160) ~[yz.class:?]
	at org.spongepowered.common.data.processor.data.entity.RepresentedItemDataProcessor.removeFrom(RepresentedItemDataProcessor.java:92) ~[RepresentedItemDataProcessor.class:1.11.2-2226-6.0.0-BETA-2110]
	at org.spongepowered.common.data.util.ValueProcessorDelegate.removeFrom(ValueProcessorDelegate.java:129) ~[ValueProcessorDelegate.class:1.11.2-2226-6.0.0-BETA-2110]
	at net.minecraft.entity.Entity.remove(Entity.java:3538) ~[sn.class:?]
	at com.me4502.slotmachines.SlotMachines$4.lambda$null$2(SlotMachines.java:333) ~[SlotMachines$4.class:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_111]
	at com.me4502.slotmachines.SlotMachines$4.lambda$accept$3(SlotMachines.java:333) ~[SlotMachines$4.class:?]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:183) ~[SchedulerBase.class:1.11.2-2226-6.0.0-BETA-2110]
	at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:66) ~[SyncScheduler.class:1.11.2-2226-6.0.0-BETA-2110]
	at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:179) ~[SchedulerBase.class:1.11.2-2226-6.0.0-BETA-2110]
	at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:165) ~[SchedulerBase.class:1.11.2-2226-6.0.0-BETA-2110]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_111]
	at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:108) [SchedulerBase.class:1.11.2-2226-6.0.0-BETA-2110]
	at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:41) [SyncScheduler.class:1.11.2-2226-6.0.0-BETA-2110]
	at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:191) [SpongeScheduler.class:1.11.2-2226-6.0.0-BETA-2110]
	at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:243) [SpongeMod.class:1.11.2-2226-6.0.0-BETA-2110]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_10_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:637) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:593) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:277) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[22:17:27] [Server thread/DEBUG] [economylite/]: playercommon: Checking if '7c47ace9-2be7-48fc-839e-36a86238b873' exists with 'economylite:yolocoin' - Cause[{Name=New account check, Object={Plugin{id=economylite, name=EconomyLite, version=2.8.0, description=An economy plugin for Sponge., source=/home/servers/sponge_mc/mods/EconomyLite-5.0.0-2.8.0.jar}}}] = true
[22:17:27] [Server thread/DEBUG] [economylite/]: playercommon: Balance of '7c47ace9-2be7-48fc-839e-36a86238b873' - Cause[{Name=Get Balance, Object={Plugin{id=economylite, name=EconomyLite, version=2.8.0, description=An economy plugin for Sponge., source=/home/servers/sponge_mc/mods/EconomyLite-5.0.0-2.8.0.jar}}}] = 4580.00
[22:17:27] [Server thread/DEBUG] [economylite/]: playercommon: Checking if '7c47ace9-2be7-48fc-839e-36a86238b873' exists with 'economylite:yolocoin' - Cause[{Name=New account check, Object={Plugin{id=economylite, name=EconomyLite, version=2.8.0, description=An economy plugin for Sponge., source=/home/servers/sponge_mc/mods/EconomyLite-5.0.0-2.8.0.jar}}}] = true
[22:17:27] [Server thread/DEBUG] [economylite/]: playercommon: Balance of '7c47ace9-2be7-48fc-839e-36a86238b873' - Cause[{Name=Get Balance, Object={Plugin{id=economylite, name=EconomyLite, version=2.8.0, description=An economy plugin for Sponge., source=/home/servers/sponge_mc/mods/EconomyLite-5.0.0-2.8.0.jar}}}] = 4580.00
[22:17:27] [Server thread/DEBUG] [economylite/]: playercommon: Checking if '7c47ace9-2be7-48fc-839e-36a86238b873' exists with 'economylite:yolocoin' - Cause[{Name=New account check, Object={Plugin{id=economylite, name=EconomyLite, version=2.8.0, description=An economy plugin for Sponge., source=/home/servers/sponge_mc/mods/EconomyLite-5.0.0-2.8.0.jar}}}] = true
[22:17:27] [Server thread/DEBUG] [economylite/]: playercommon: Balance of '7c47ace9-2be7-48fc-839e-36a86238b873' - Cause[{Name=Get Balance, Object={Plugin{id=economylite, name=EconomyLite, version=2.8.0, description=An economy plugin for Sponge., source=/home/servers/sponge_mc/mods/EconomyLite-5.0.0-2.8.0.jar}}}] = 4580.00
[22:17:27] [Server thread/DEBUG] [economylite/]: playercommon: Checking if '7c47ace9-2be7-48fc-839e-36a86238b873' exists with 'economylite:yolocoin' - Cause[{Name=New account check, Object={Plugin{id=economylite, name=EconomyLite, version=2.8.0, description=An economy plugin for Sponge., source=/home/servers/sponge_mc/mods/EconomyLite-5.0.0-2.8.0.jar}}}] = true
[22:17:27] [Server thread/DEBUG] [economylite/]: playercommon: Balance of '7c47ace9-2be7-48fc-839e-36a86238b873' - Cause[{Name=Get Balance, Object={Plugin{id=economylite, name=EconomyLite, version=2.8.0, description=An economy plugin for Sponge., source=/home/servers/sponge_mc/mods/EconomyLite-5.0.0-2.8.0.jar}}}] = 4580.00
[22:17:28] [HikariPool-3 housekeeper/DEBUG] [com.zaxxer.hikari.pool.HikariPool/sponge]: HikariPool-3 - Pool stats (total=9, active=0, idle=9, waiting=0)
```

It spam's the balance things in console btw.

Greetz,
Hannes

**Comment by crymates** [comment]
Using the newest sponge release `spongeforge-1.11.2-2226-6.0.0-BETA-2110`.

I hope u get it fixed soon, ur plugin rocks!

**Comment by me4502** [comment]
This is a Sponge bug, I'll add it to my todo list to fix.

**Comment by crymates** [comment]
Thx alot ;]

**Comment by me4502** [comment]
This was fixed a while ago, so I'm closing it.
